# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8981fdfc226201bb8ec524cdd789168c7b1b532f2a4258c9ea4d79504db992f37bab24d9a9d49fcab3dd024bbaca845b479879e4a1e525e52e705a69624d5b27

test:
  secret_key_base: 4f748b33bcf57546c3e4c433a974038e7d95f0f21062a56cef90d014a6f581150b952ca19ba240e11476d54ddac32de81cae28ed0144ff00de4ab5c09c417ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
