# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b4407697388257c049ff3b6185631925756d324a47924981a011cc61f64db5a1f26e83c22627284bf0c86488074f9626433ba5bcd2f5649be59b670fba0fee

test:
  secret_key_base: 257fe141fcae22d34c9e11736b521c8eaa05365321515f8a9b6828a30404552b5ca474fef68d88a37cd616ffa825ee5b71e5b484e450b97699c08d89a051016c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
